# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZWJiODY4M2JhZmU5YmQzZTRjNDBhN2I0NDI2NTRlNTBhZjgyYjE2NGJjZDJjNjIzOWE0ZWFlMmU1YzdlZmZhZGU3ZDc2NjVhOGExZmE1M2ViNmYwMWUwY2JlMDcxZDllYTE2YzhmMjZkM2I1MzRlZTA4YTEzODJiZjAzYWQyMWQ=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
